// Generated by https://quicktype.io

export interface Comic {
  month: string
  num: number
  link: string
  year: string
  news: string
  safe_title: string
  transcript: string
  alt: string
  img: string
  title: string
  day: string
}

export interface ResponseComicAdapter {
  alt: string
  img: string
  num: number
  title: string
  transcript: string
  stars: number
}
